// Distinct Category Color Design System for 醫定要健康 (Clear, Vibrant, High-Contrast & Harmonious)

export interface CategoryTheme {
  id: string;
  name: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  pillActiveBg: string;
  pillActiveText: string;
  pillInactiveHover: string;
  dotColor: string;
  iconBg: string;
  iconColor: string;
  cardBorderHover: string;
  accentGradient: string;
}

// 1. Navigation Tab Colors
export const NAV_THEMES: Record<string, {
  activeBg: string;
  activeText: string;
  activeBorder: string;
  badge: string;
  dot: string;
  iconColor: string;
}> = {
  home: {
    activeBg: 'bg-[#2C3324]',
    activeText: 'text-white',
    activeBorder: 'border-[#2C3324]',
    badge: 'bg-[#E9F0E8] text-[#2C3324]',
    dot: 'bg-[#8BA888]',
    iconColor: 'text-[#8BA888]',
  },
  rescue: {
    activeBg: 'bg-rose-600',
    activeText: 'text-white',
    activeBorder: 'border-rose-600',
    badge: 'bg-rose-100 text-rose-800 border border-rose-200',
    dot: 'bg-rose-500',
    iconColor: 'text-rose-600',
  },
  journals: {
    activeBg: 'bg-amber-600',
    activeText: 'text-white',
    activeBorder: 'border-amber-600',
    badge: 'bg-amber-100 text-amber-900 border border-amber-200',
    dot: 'bg-amber-500',
    iconColor: 'text-amber-600',
  },
  learning: {
    activeBg: 'bg-emerald-700',
    activeText: 'text-white',
    activeBorder: 'border-emerald-700',
    badge: 'bg-emerald-100 text-emerald-900 border border-emerald-200',
    dot: 'bg-emerald-500',
    iconColor: 'text-emerald-600',
  },
  soundscapes: {
    activeBg: 'bg-sky-600',
    activeText: 'text-white',
    activeBorder: 'border-sky-600',
    badge: 'bg-sky-100 text-sky-900 border border-sky-200',
    dot: 'bg-sky-500',
    iconColor: 'text-sky-600',
  },
  'audio-guides': {
    activeBg: 'bg-indigo-600',
    activeText: 'text-white',
    activeBorder: 'border-indigo-600',
    badge: 'bg-indigo-100 text-indigo-900 border border-indigo-200',
    dot: 'bg-indigo-500',
    iconColor: 'text-indigo-600',
  },
  insights: {
    activeBg: 'bg-teal-700',
    activeText: 'text-white',
    activeBorder: 'border-teal-700',
    badge: 'bg-teal-100 text-teal-900 border border-teal-200',
    dot: 'bg-teal-500',
    iconColor: 'text-teal-600',
  },
  care: {
    activeBg: 'bg-purple-700',
    activeText: 'text-white',
    activeBorder: 'border-purple-700',
    badge: 'bg-purple-100 text-purple-900 border border-purple-200',
    dot: 'bg-purple-500',
    iconColor: 'text-purple-600',
  },
};

// 2. Rescue Category Color Map
export const RESCUE_CATEGORY_THEMES: Record<string, CategoryTheme> = {
  all: {
    id: 'all',
    name: '全部',
    badgeBg: 'bg-[#F1F5EF]',
    badgeText: 'text-[#2C3324]',
    badgeBorder: 'border-[#C9D6C8]',
    pillActiveBg: 'bg-[#2C3324]',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-[#2C3324] hover:bg-[#F9F8F4]',
    dotColor: 'bg-[#2C3324]',
    iconBg: 'bg-[#E9F0E8]',
    iconColor: 'text-[#2C3324]',
    cardBorderHover: 'hover:border-[#2C3324]',
    accentGradient: 'from-[#2C3324] to-[#5A6352]',
  },
  anxiety: {
    id: 'anxiety',
    name: '焦慮與心悸',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-900',
    badgeBorder: 'border-amber-200',
    pillActiveBg: 'bg-amber-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-amber-400 hover:bg-amber-50/60 hover:text-amber-900',
    dotColor: 'bg-amber-500',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-700',
    cardBorderHover: 'hover:border-amber-400',
    accentGradient: 'from-amber-500 to-orange-500',
  },
  overwhelm: {
    id: 'overwhelm',
    name: '大腦過載與宕機',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-900',
    badgeBorder: 'border-rose-200',
    pillActiveBg: 'bg-rose-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-rose-400 hover:bg-rose-50/60 hover:text-rose-900',
    dotColor: 'bg-rose-500',
    iconBg: 'bg-rose-100',
    iconColor: 'text-rose-700',
    cardBorderHover: 'hover:border-rose-400',
    accentGradient: 'from-rose-500 to-pink-500',
  },
  burnout: {
    id: 'burnout',
    name: '職場重壓與倦怠',
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-900',
    badgeBorder: 'border-orange-200',
    pillActiveBg: 'bg-orange-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-orange-400 hover:bg-orange-50/60 hover:text-orange-900',
    dotColor: 'bg-orange-500',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-700',
    cardBorderHover: 'hover:border-orange-400',
    accentGradient: 'from-orange-500 to-red-500',
  },
  procrastination: {
    id: 'procrastination',
    name: '拖延與動力啟動',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-200',
    pillActiveBg: 'bg-indigo-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-indigo-400 hover:bg-indigo-50/60 hover:text-indigo-900',
    dotColor: 'bg-indigo-500',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-700',
    cardBorderHover: 'hover:border-indigo-400',
    accentGradient: 'from-indigo-500 to-blue-500',
  },
  criticism: {
    id: 'criticism',
    name: '批評與自我懷疑',
    badgeBg: 'bg-violet-50',
    badgeText: 'text-violet-900',
    badgeBorder: 'border-violet-200',
    pillActiveBg: 'bg-violet-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-violet-400 hover:bg-violet-50/60 hover:text-violet-900',
    dotColor: 'bg-violet-500',
    iconBg: 'bg-violet-100',
    iconColor: 'text-violet-700',
    cardBorderHover: 'hover:border-violet-400',
    accentGradient: 'from-violet-500 to-purple-500',
  },
  anger: {
    id: 'anger',
    name: '憤怒與煩躁降溫',
    badgeBg: 'bg-red-50',
    badgeText: 'text-red-900',
    badgeBorder: 'border-red-200',
    pillActiveBg: 'bg-red-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-red-400 hover:bg-red-50/60 hover:text-red-900',
    dotColor: 'bg-red-500',
    iconBg: 'bg-red-100',
    iconColor: 'text-red-700',
    cardBorderHover: 'hover:border-red-400',
    accentGradient: 'from-red-600 to-rose-600',
  },
  relationships: {
    id: 'relationships',
    name: '關係衝突與界線',
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-900',
    badgeBorder: 'border-teal-200',
    pillActiveBg: 'bg-teal-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-teal-400 hover:bg-teal-50/60 hover:text-teal-900',
    dotColor: 'bg-teal-500',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-700',
    cardBorderHover: 'hover:border-teal-400',
    accentGradient: 'from-teal-500 to-emerald-500',
  },
  grief: {
    id: 'grief',
    name: '悲傷低落與失落',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-900',
    badgeBorder: 'border-sky-200',
    pillActiveBg: 'bg-sky-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-sky-400 hover:bg-sky-50/60 hover:text-sky-900',
    dotColor: 'bg-sky-500',
    iconBg: 'bg-sky-100',
    iconColor: 'text-sky-700',
    cardBorderHover: 'hover:border-sky-400',
    accentGradient: 'from-sky-500 to-cyan-500',
  },
  sleep: {
    id: 'sleep',
    name: '失眠與睡前雜念',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-900',
    badgeBorder: 'border-purple-200',
    pillActiveBg: 'bg-purple-700',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-purple-400 hover:bg-purple-50/60 hover:text-purple-900',
    dotColor: 'bg-purple-500',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-700',
    cardBorderHover: 'hover:border-purple-400',
    accentGradient: 'from-purple-600 to-indigo-700',
  },
  focus: {
    id: 'focus',
    name: '專注提神與定心',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-900',
    badgeBorder: 'border-emerald-200',
    pillActiveBg: 'bg-emerald-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-emerald-400 hover:bg-emerald-50/60 hover:text-emerald-900',
    dotColor: 'bg-emerald-500',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-700',
    cardBorderHover: 'hover:border-emerald-400',
    accentGradient: 'from-emerald-500 to-teal-500',
  },
};

// 3. Learning Paths Category Color Map
export const LEARNING_CATEGORY_THEMES: Record<string, CategoryTheme> = {
  all: {
    id: 'all',
    name: '全部',
    badgeBg: 'bg-[#F1F5EF]',
    badgeText: 'text-[#2C3324]',
    badgeBorder: 'border-[#C9D6C8]',
    pillActiveBg: 'bg-[#2C3324]',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-[#2C3324] hover:bg-[#F9F8F4]',
    dotColor: 'bg-[#2C3324]',
    iconBg: 'bg-[#E9F0E8]',
    iconColor: 'text-[#2C3324]',
    cardBorderHover: 'hover:border-[#2C3324]',
    accentGradient: 'from-[#2C3324] to-[#5A6352]',
  },
  'stress-burnout': {
    id: 'stress-burnout',
    name: '壓力與抗倦怠',
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-900',
    badgeBorder: 'border-orange-200',
    pillActiveBg: 'bg-orange-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-orange-400 hover:bg-orange-50/60 hover:text-orange-900',
    dotColor: 'bg-orange-500',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-700',
    cardBorderHover: 'hover:border-orange-400',
    accentGradient: 'from-orange-500 to-amber-500',
  },
  'emotion-regulation': {
    id: 'emotion-regulation',
    name: '情緒調節與韌性',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-900',
    badgeBorder: 'border-rose-200',
    pillActiveBg: 'bg-rose-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-rose-400 hover:bg-rose-50/60 hover:text-rose-900',
    dotColor: 'bg-rose-500',
    iconBg: 'bg-rose-100',
    iconColor: 'text-rose-700',
    cardBorderHover: 'hover:border-rose-400',
    accentGradient: 'from-rose-500 to-pink-500',
  },
  'work-relationships': {
    id: 'work-relationships',
    name: '職場人際與界線',
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-900',
    badgeBorder: 'border-teal-200',
    pillActiveBg: 'bg-teal-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-teal-400 hover:bg-teal-50/60 hover:text-teal-900',
    dotColor: 'bg-teal-500',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-700',
    cardBorderHover: 'hover:border-teal-400',
    accentGradient: 'from-teal-500 to-cyan-500',
  },
  'self-worth': {
    id: 'self-worth',
    name: '自信與自我關懷',
    badgeBg: 'bg-pink-50',
    badgeText: 'text-pink-900',
    badgeBorder: 'border-pink-200',
    pillActiveBg: 'bg-pink-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-pink-400 hover:bg-pink-50/60 hover:text-pink-900',
    dotColor: 'bg-pink-500',
    iconBg: 'bg-pink-100',
    iconColor: 'text-pink-700',
    cardBorderHover: 'hover:border-pink-400',
    accentGradient: 'from-pink-500 to-rose-400',
  },
  'sleep-focus': {
    id: 'sleep-focus',
    name: '專注提升與深度睡眠',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-200',
    pillActiveBg: 'bg-indigo-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-indigo-400 hover:bg-indigo-50/60 hover:text-indigo-900',
    dotColor: 'bg-indigo-500',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-700',
    cardBorderHover: 'hover:border-indigo-400',
    accentGradient: 'from-indigo-500 to-purple-500',
  },
};

// 4. Journals Category Color Map
export const JOURNAL_CATEGORY_THEMES: Record<string, CategoryTheme> = {
  all: {
    id: 'all',
    name: '全部',
    badgeBg: 'bg-[#F1F5EF]',
    badgeText: 'text-[#2C3324]',
    badgeBorder: 'border-[#C9D6C8]',
    pillActiveBg: 'bg-[#2C3324]',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-[#2C3324] hover:bg-[#F9F8F4]',
    dotColor: 'bg-[#2C3324]',
    iconBg: 'bg-[#E9F0E8]',
    iconColor: 'text-[#2C3324]',
    cardBorderHover: 'hover:border-[#2C3324]',
    accentGradient: 'from-[#2C3324] to-[#5A6352]',
  },
  gratitude: {
    id: 'gratitude',
    name: '感恩與日常反思',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-900',
    badgeBorder: 'border-amber-200',
    pillActiveBg: 'bg-amber-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-amber-400 hover:bg-amber-50/60 hover:text-amber-900',
    dotColor: 'bg-amber-500',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-700',
    cardBorderHover: 'hover:border-amber-400',
    accentGradient: 'from-amber-400 to-amber-600',
  },
  cbt: {
    id: 'cbt',
    name: 'CBT 認知重塑',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-200',
    pillActiveBg: 'bg-indigo-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-indigo-400 hover:bg-indigo-50/60 hover:text-indigo-900',
    dotColor: 'bg-indigo-500',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-700',
    cardBorderHover: 'hover:border-indigo-400',
    accentGradient: 'from-indigo-500 to-blue-600',
  },
  'stress-burnout': {
    id: 'stress-burnout',
    name: '壓力與防倦怠',
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-900',
    badgeBorder: 'border-orange-200',
    pillActiveBg: 'bg-orange-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-orange-400 hover:bg-orange-50/60 hover:text-orange-900',
    dotColor: 'bg-orange-500',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-700',
    cardBorderHover: 'hover:border-orange-400',
    accentGradient: 'from-orange-500 to-red-500',
  },
  'self-compassion': {
    id: 'self-compassion',
    name: '自我關懷與接納',
    badgeBg: 'bg-pink-50',
    badgeText: 'text-pink-900',
    badgeBorder: 'border-pink-200',
    pillActiveBg: 'bg-pink-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-pink-400 hover:bg-pink-50/60 hover:text-pink-900',
    dotColor: 'bg-pink-500',
    iconBg: 'bg-pink-100',
    iconColor: 'text-pink-700',
    cardBorderHover: 'hover:border-pink-400',
    accentGradient: 'from-pink-500 to-rose-400',
  },
  emotions: {
    id: 'emotions',
    name: '情緒疏導與覺察',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-900',
    badgeBorder: 'border-rose-200',
    pillActiveBg: 'bg-rose-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-rose-400 hover:bg-rose-50/60 hover:text-rose-900',
    dotColor: 'bg-rose-500',
    iconBg: 'bg-rose-100',
    iconColor: 'text-rose-700',
    cardBorderHover: 'hover:border-rose-400',
    accentGradient: 'from-rose-500 to-pink-600',
  },
  relationships: {
    id: 'relationships',
    name: '人際關係與界線',
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-900',
    badgeBorder: 'border-teal-200',
    pillActiveBg: 'bg-teal-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-teal-400 hover:bg-teal-50/60 hover:text-teal-900',
    dotColor: 'bg-teal-500',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-700',
    cardBorderHover: 'hover:border-teal-400',
    accentGradient: 'from-teal-500 to-cyan-600',
  },
  sleep: {
    id: 'sleep',
    name: '睡眠與夜間安心',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-900',
    badgeBorder: 'border-purple-200',
    pillActiveBg: 'bg-purple-700',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-purple-400 hover:bg-purple-50/60 hover:text-purple-900',
    dotColor: 'bg-purple-500',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-700',
    cardBorderHover: 'hover:border-purple-400',
    accentGradient: 'from-purple-600 to-indigo-700',
  },
  'growth-decisions': {
    id: 'growth-decisions',
    name: '目標決策與成長',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-900',
    badgeBorder: 'border-emerald-200',
    pillActiveBg: 'bg-emerald-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-emerald-400 hover:bg-emerald-50/60 hover:text-emerald-900',
    dotColor: 'bg-emerald-500',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-700',
    cardBorderHover: 'hover:border-emerald-400',
    accentGradient: 'from-emerald-500 to-teal-600',
  },
};

// 5. Meditations / Soundscapes Category Color Map
export const MEDITATION_CATEGORY_THEMES: Record<string, CategoryTheme> = {
  all: {
    id: 'all',
    name: '全部',
    badgeBg: 'bg-[#F1F5EF]',
    badgeText: 'text-[#2C3324]',
    badgeBorder: 'border-[#C9D6C8]',
    pillActiveBg: 'bg-[#2C3324]',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-[#2C3324] hover:bg-[#F9F8F4]',
    dotColor: 'bg-[#2C3324]',
    iconBg: 'bg-[#E9F0E8]',
    iconColor: 'text-[#2C3324]',
    cardBorderHover: 'hover:border-[#2C3324]',
    accentGradient: 'from-[#2C3324] to-[#5A6352]',
  },
  'inner-calm': {
    id: 'inner-calm',
    name: '內在寧靜',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-900',
    badgeBorder: 'border-emerald-200',
    pillActiveBg: 'bg-emerald-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-emerald-400 hover:bg-emerald-50/60 hover:text-emerald-900',
    dotColor: 'bg-emerald-500',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-700',
    cardBorderHover: 'hover:border-emerald-400',
    accentGradient: 'from-emerald-500 to-teal-500',
  },
  'body-scan': {
    id: 'body-scan',
    name: '身體掃描',
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-900',
    badgeBorder: 'border-teal-200',
    pillActiveBg: 'bg-teal-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-teal-400 hover:bg-teal-50/60 hover:text-teal-900',
    dotColor: 'bg-teal-500',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-700',
    cardBorderHover: 'hover:border-teal-400',
    accentGradient: 'from-teal-500 to-cyan-500',
  },
  emotion: {
    id: 'emotion',
    name: '情緒包容',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-900',
    badgeBorder: 'border-rose-200',
    pillActiveBg: 'bg-rose-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-rose-400 hover:bg-rose-50/60 hover:text-rose-900',
    dotColor: 'bg-rose-500',
    iconBg: 'bg-rose-100',
    iconColor: 'text-rose-700',
    cardBorderHover: 'hover:border-rose-400',
    accentGradient: 'from-rose-500 to-pink-500',
  },
  'loving-kindness': {
    id: 'loving-kindness',
    name: '慈心自我',
    badgeBg: 'bg-pink-50',
    badgeText: 'text-pink-900',
    badgeBorder: 'border-pink-200',
    pillActiveBg: 'bg-pink-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-pink-400 hover:bg-pink-50/60 hover:text-pink-900',
    dotColor: 'bg-pink-500',
    iconBg: 'bg-pink-100',
    iconColor: 'text-pink-700',
    cardBorderHover: 'hover:border-pink-400',
    accentGradient: 'from-pink-500 to-rose-400',
  },
  sleep: {
    id: 'sleep',
    name: '深度睡眠',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-200',
    pillActiveBg: 'bg-indigo-700',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-indigo-400 hover:bg-indigo-50/60 hover:text-indigo-900',
    dotColor: 'bg-indigo-500',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-700',
    cardBorderHover: 'hover:border-indigo-400',
    accentGradient: 'from-indigo-600 to-purple-600',
  },
  focus: {
    id: 'focus',
    name: '專注力',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-900',
    badgeBorder: 'border-amber-200',
    pillActiveBg: 'bg-amber-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-amber-400 hover:bg-amber-50/60 hover:text-amber-900',
    dotColor: 'bg-amber-500',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-700',
    cardBorderHover: 'hover:border-amber-400',
    accentGradient: 'from-amber-500 to-orange-500',
  },
};

// 6. Audio Guides Category Color Map
export const AUDIO_CATEGORY_THEMES: Record<string, CategoryTheme> = {
  all: {
    id: 'all',
    name: '全部',
    badgeBg: 'bg-[#F1F5EF]',
    badgeText: 'text-[#2C3324]',
    badgeBorder: 'border-[#C9D6C8]',
    pillActiveBg: 'bg-[#2C3324]',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-[#2C3324] hover:bg-[#F9F8F4]',
    dotColor: 'bg-[#2C3324]',
    iconBg: 'bg-[#E9F0E8]',
    iconColor: 'text-[#2C3324]',
    cardBorderHover: 'hover:border-[#2C3324]',
    accentGradient: 'from-[#2C3324] to-[#5A6352]',
  },
  work: {
    id: 'work',
    name: '職場挑戰',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-200',
    pillActiveBg: 'bg-indigo-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-indigo-400 hover:bg-indigo-50/60 hover:text-indigo-900',
    dotColor: 'bg-indigo-500',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-700',
    cardBorderHover: 'hover:border-indigo-400',
    accentGradient: 'from-indigo-500 to-blue-600',
  },
  calm: {
    id: 'calm',
    name: '平復情緒',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-900',
    badgeBorder: 'border-emerald-200',
    pillActiveBg: 'bg-emerald-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-emerald-400 hover:bg-emerald-50/60 hover:text-emerald-900',
    dotColor: 'bg-emerald-500',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-700',
    cardBorderHover: 'hover:border-emerald-400',
    accentGradient: 'from-emerald-500 to-teal-500',
  },
  confidence: {
    id: 'confidence',
    name: '自信重塑',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-900',
    badgeBorder: 'border-amber-200',
    pillActiveBg: 'bg-amber-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-amber-400 hover:bg-amber-50/60 hover:text-amber-900',
    dotColor: 'bg-amber-500',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-700',
    cardBorderHover: 'hover:border-amber-400',
    accentGradient: 'from-amber-500 to-orange-500',
  },
  sleep: {
    id: 'sleep',
    name: '睡眠休息',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-900',
    badgeBorder: 'border-purple-200',
    pillActiveBg: 'bg-purple-700',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-purple-400 hover:bg-purple-50/60 hover:text-purple-900',
    dotColor: 'bg-purple-500',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-700',
    cardBorderHover: 'hover:border-purple-400',
    accentGradient: 'from-purple-600 to-indigo-700',
  },
  focus: {
    id: 'focus',
    name: '專注心流',
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-900',
    badgeBorder: 'border-teal-200',
    pillActiveBg: 'bg-teal-600',
    pillActiveText: 'text-white',
    pillInactiveHover: 'hover:border-teal-400 hover:bg-teal-50/60 hover:text-teal-900',
    dotColor: 'bg-teal-500',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-700',
    cardBorderHover: 'hover:border-teal-400',
    accentGradient: 'from-teal-500 to-emerald-500',
  },
};

// Generic safe getters
export function getRescueTheme(cat?: string): CategoryTheme {
  return (cat && RESCUE_CATEGORY_THEMES[cat]) || RESCUE_CATEGORY_THEMES.all;
}

export function getLearningTheme(cat?: string): CategoryTheme {
  return (cat && LEARNING_CATEGORY_THEMES[cat]) || LEARNING_CATEGORY_THEMES.all;
}

export function getJournalTheme(cat?: string): CategoryTheme {
  return (cat && JOURNAL_CATEGORY_THEMES[cat]) || JOURNAL_CATEGORY_THEMES.all;
}

export function getMeditationTheme(cat?: string): CategoryTheme {
  return (cat && MEDITATION_CATEGORY_THEMES[cat]) || MEDITATION_CATEGORY_THEMES.all;
}

export function getAudioTheme(cat?: string): CategoryTheme {
  return (cat && AUDIO_CATEGORY_THEMES[cat]) || AUDIO_CATEGORY_THEMES.all;
}
